services:
  - type: web
    name: kleara-clinic-api
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: cd server && npm install
    startCommand: cd server && node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://client-six-tau-64.vercel.app
    autoDeploy: true
